force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Client is the person who is receiving the Service</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Key__c.field-meta.xml
<CustomField>
    <fullName>Client_Key__c</fullName>
    <description>This is a number or code assigned to each individual client referred to the commissioned organisation. The client identifier must be unique and stable for each individual within the Provider Organisation. Assigned by either the PHN or Provider Organisation depending on local procedures.</description>
    <label>Client Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Tags__c.field-meta.xml
<CustomField>
    <fullName>Client_Tags__c</fullName>
    <description>List of tags for the client.</description>
    <label>Client Tags</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Country_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Country_Of_Birth__c</fullName>
    <label>Country Of Birth</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1101:	Australia</fullName>
            </value>
            <value>
                <fullName>1102:	Norfolk Island</fullName>
            </value>
            <value>
                <fullName>1199:	Australian External Territories, nec</fullName>
            </value>
            <value>
                <fullName>1201:	New Zealand</fullName>
            </value>
            <value>
                <fullName>1301:	New Caledonia</fullName>
            </value>
            <value>
                <fullName>1302:	Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>1303:	Solomon Islands</fullName>
            </value>
            <value>
                <fullName>1304:	Vanuatu</fullName>
            </value>
            <value>
                <fullName>1401:	Guam</fullName>
            </value>
            <value>
                <fullName>1402:	Kiribati</fullName>
            </value>
            <value>
                <fullName>1403:	Marshall Islands</fullName>
            </value>
            <value>
                <fullName>1404:	Micronesia, Federated States of</fullName>
            </value>
            <value>
                <fullName>1405:	Nauru</fullName>
            </value>
            <value>
                <fullName>1406:	Northern Mariana Islands</fullName>
            </value>
            <value>
                <fullName>1407:	Palau</fullName>
            </value>
            <value>
                <fullName>1501:	Cook Islands</fullName>
            </value>
            <value>
                <fullName>1502:	Fiji</fullName>
            </value>
            <value>
                <fullName>1503:	French Polynesia</fullName>
            </value>
            <value>
                <fullName>1504:	Niue</fullName>
            </value>
            <value>
                <fullName>1505:	Samoa</fullName>
            </value>
            <value>
                <fullName>1506:	Samoa, American</fullName>
            </value>
            <value>
                <fullName>1507:	Tokelau</fullName>
            </value>
            <value>
                <fullName>1508:	Tonga</fullName>
            </value>
            <value>
                <fullName>1511:	Tuvalu</fullName>
            </value>
            <value>
                <fullName>1512:	Wallis and Futuna</fullName>
            </value>
            <value>
                <fullName>1513:	Pitcairn Islands</fullName>
            </value>
            <value>
                <fullName>1599:	Polynesia (excludes Hawaii), nec</fullName>
            </value>
            <value>
                <fullName>1601:	Adelie Land (France)</fullName>
            </value>
            <value>
                <fullName>1602:	Argentinian Antarctic Territory</fullName>
            </value>
            <value>
                <fullName>1603:	Australian Antarctic Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <description>The date on which an individual was born.</description>
    <label>Date Of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Est_Date_of_Birth_Flag__c.field-meta.xml
<CustomField>
    <fullName>Est_Date_of_Birth_Flag__c</fullName>
    <label>Estimated Date of Birth Flag</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:	Date of birth is accurate</fullName>
            </value>
            <value>
                <fullName>2:	Date of birth is an estimate</fullName>
            </value>
            <value>
                <fullName>8:	Date of birth is a ‘dummy’ date (ie, 09099999)</fullName>
            </value>
            <value>
                <fullName>9:	Accuracy of stated date of birth is not know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/main_lang_at_home__c.field-meta.xml
<CustomField>
    <fullName>main_lang_at_home__c</fullName>
    <label>Main Language Spoken at Home</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1101:	Gaelic (Scotland)</fullName>
            </value>
            <value>
                <fullName>1102:	Irish</fullName>
            </value>
            <value>
                <fullName>1103:	Welsh</fullName>
            </value>
            <value>
                <fullName>1199:	Celtic, nec</fullName>
            </value>
            <value>
                <fullName>1201:	English</fullName>
            </value>
            <value>
                <fullName>1301:	German</fullName>
            </value>
            <value>
                <fullName>1302:	Letzeburgish</fullName>
            </value>
            <value>
                <fullName>1303:	Yiddish</fullName>
            </value>
            <value>
                <fullName>1401:	Dutch</fullName>
            </value>
            <value>
                <fullName>1402:	Frisian</fullName>
            </value>
            <value>
                <fullName>1403:	Afrikaans</fullName>
            </value>
            <value>
                <fullName>1501:	Danish</fullName>
            </value>
            <value>
                <fullName>1502:	Icelandic</fullName>
            </value>
            <value>
                <fullName>1503:	Norwegian</fullName>
            </value>
            <value>
                <fullName>1504:	Swedish</fullName>
            </value>
            <value>
                <fullName>1599:	Scandinavian, nec</fullName>
            </value>
            <value>
                <fullName>1601:	Estonian</fullName>
            </value>
            <value>
                <fullName>1602:	Finnish</fullName>
            </value>
            <value>
                <fullName>1699:	Finnish and Related Languages, nec</fullName>
            </value>
            <value>
                <fullName>2101:	French</fullName>
            </value>
            <value>
                <fullName>2201:	Greek</fullName>
            </value>
            <value>
                <fullName>2301:	Catalan</fullName>
            </value>
            <value>
                <fullName>2302:	Portuguese</fullName>
            </value>
            <value>
                <fullName>2303:	Spanish</fullName>
            </value>
            <value>
                <fullName>2399:	Iberian Romance, nec</fullName>
            </value>
            <value>
                <fullName>2401:	Italian</fullName>
            </value>
            <value>
                <fullName>2501:	Maltese</fullName>
            </value>
            <value>
                <fullName>2901:	Basque</fullName>
            </value>
            <value>
                <fullName>2902:	Latin</fullName>
            </value>
            <value>
                <fullName>2999:	Other Southern European Languages, nec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/prof_english__c.field-meta.xml
<CustomField>
    <fullName>prof_english__c</fullName>
    <label>Proficiency in Spoken English</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0:	Not applicable (persons under 5 years of age or who speak only English)</fullName>
            </value>
            <value>
                <fullName>1:	Very well</fullName>
            </value>
            <value>
                <fullName>2:	Well</fullName>
            </value>
            <value>
                <fullName>3:	Not well</fullName>
            </value>
            <value>
                <fullName>4:	Not at all</fullName>
            </value>
            <value>
                <fullName>9:	Not stated/inadequately described</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/slk__c.field-meta.xml
<CustomField>
    <fullName>slk__c</fullName>
    <description>A key that enables two or more records belonging to the same individual to be brought together.</description>
    <label>Statistical Linkage Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClientController.cls
public with sharing class ClientController {

    public ClientController() {

    }

    /**
     * This is just simple save action.
     */
    public void saveRecord(String clientKey, String clientName, String clientGender, 
            String clientTags, String countryOfBirth, Date dateOfBirth, String estDateOfBirthFlag, 
            String mainLangAtHome, String orgPath, String profEnglish, String slk){
        
        Client__c client = new Client__c(Client_Key__c = clientKey, Name = clientName, 
                            Client_Tags__c = clientTags, Country_Of_Birth__c = countryOfBirth,
                            Date_Of_Birth__c = dateOfBirth, Est_Date_Of_Birth_Flag__c = estDateOfBirthFlag,
                            Main_Lang_At_Home__c = mainLangAtHome, Organisation_Path__c = orgPath,
                            Prof_English__c = profEnglish, Slk__c = slk);

        insert client;
        
            
    }

    public void deleteClient(Id id) {

    }

    public List<Client__c> getClientByName (String name){
        List<Client__c> clients = new List<Client__c>();
        return clients;
    }

    public List<Client__c> getClientById (Id id) {
        List<Client__c> clients = new List<Client__c>();
        return clients;
    }

    public void updateClient(Id id) {

    }

}